spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:connectlydb}
    username: ${MYSQL_USER:mehdi}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${MYSQL_USER:mehdi}
    password: ${MYSQL_PASSWORD:1234}
    baseline-description: init
    baseline-version: 0

application:
  data:
    init: true